Fix: RabbitMQ is available to connect while all permissions are not configured yet.
egal/rabbitmq pull request #4
Opened 2021-12-09 06:56 UTC by annstgn

2021-12-23 04:16 UTC, rollsover requested changes
Не нравится пока мне это решение

2021-12-23 04:16 UTC, rollsover commented on base/rabbitmq.config
> +].
Пустая строка

2021-12-23 04:16 UTC, rollsover commented on base/definitions.json
> +}
Пустая строка

2021-12-23 04:16 UTC, rollsover commented on base/Dockerfile
> +RUN sed -i "s/RABBITMQ_USER/${RABBITMQ_USER}/g" /etc/rabbitmq/definitions.json
Это не будет так работать. Оно не будет заменяться в режиме реального времени. Это надо кидать в CMD

Может надо уже разобраться с entrypoint?

2021-12-23 05:19 UTC, annstgn commented on base/Dockerfile
> +RUN sed -i "s/RABBITMQ_USER/${RABBITMQ_USER}/g" /etc/rabbitmq/definitions.json
Да, поняла. Перенесу в cmd. Ещё видела вариант, когда команды для запуска помещают в bash скрипт и его запуск в entrypoint.

2021-12-24 11:34 UTC, rollsover requested changes
Плагины не динамические 

В конце файлов нет пустых строк

2021-12-24 11:35 UTC, rollsover requested changes
Посмотри коробочные конфиги, может там уже все есть, а ты перезаписываешь.

Посмотри какие коробочные есть ENV параметры

2021-12-24 11:35 UTC, rollsover commented on management/definitions.json
> +      "user": "user",
Статика

2021-12-27 04:03 UTC, annstgn commented
> Посмотри коробочные конфиги, может там уже все есть, а ты перезаписываешь.
> 
> Посмотри какие коробочные есть ENV параметры

Коробочных конфигов нет таких, так что все ок

2021-12-27 04:04 UTC, annstgn commented
> > Посмотри коробочные конфиги, может там уже все есть, а ты перезаписываешь.
> > Посмотри какие коробочные есть ENV параметры
> 
> Коробочных конфигов нет таких, так что все ок

вот все, что есть 
![image](https://user-images.githubusercontent.com/91238426/147433199-dfc297c1-4471-4597-953b-553bb0fe53b3.png)

2021-12-28 05:18 UTC, rollsover approved these changes

2021-12-28 05:35 UTC, merged